FROM openjdk:11-jdk AS builder
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJar
FROM openjdk:11-slim
VOLUME /tmp
ENTRYPOINT ["java", "-jar", "dalkom.jar", "-Dspring.profiles.active=prod", "-Dspring.config.location=classpath:./src/main/resources/application.yml,file:./src/main/resources/application.yml"]