#spring:
#  application:
#  datasource:
#    url: ${_DATABASE_URL}
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ${Local_DATABASE_USERNAME}
#    password: ${Local_DATABASE_PASSWORD}
#    jpa:
#      database: mysql
#      open-in-view: false
#      show-sql: true
#      hibernate:
#        properties:
#          hibernate:
#            format_sql: true
#
#  # 로깅 설정
#  logging:
#    level:
#      org.hibernate.SQL: debug
#      org.hibernate.type: trace
#
#  # 서버 포트 설정
#server:
#  port: 8080
#
## Eureka 클라이언트 설정
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka #
#
#
#jwt:
#  key:
#    #스프링부트 마스터하고싶다
#    access: ${JWT_ACCESS_KEY}
#    #스프링부트 마스터하고싶다 진짜로
#    refresh: ${JWT_ACCESS_KEY}
#  max-age:
#    access: 604800 # 60 * 30 테스트를 위해 원래는 1800이던걸 30으로 줄여놨습니다.
#    refresh: 604800 # 60 * 60 * 24 * 7
#
