spring:
  application:
  datasource:
    url: ${LOCAL_DATABASE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}
    jpa:
      database: mysql
      open-in-view: false
      show-sql: true
      hibernate:

        #table 자동생성
        ddl-auto:
        properties:
          hibernate:
            format_sql: true

  # 로깅 설정
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  # 서버 포트 설정
server:
  port: 8080

jwt:
  key:
    access: ${JWT_ACCESS_KEY}
    refresh: ${JWT_REFRESH_KEY}
  max-age:
    access: 604800
    refresh: 604800
    

