spring:
  application :
  redis:
    host: ${PROD_REDIS_IP}
    port: ${PROD_REDIS_PORT}
  datasource:
    url: ${PROD_DATABASE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${PROD_DATABASE_USERNAME}
    password: ${PROD_DATABASE_PASSWORD}
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true

  # 로깅 설정
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  # 서버 포트 설정
server:
  port: 8080

jwt:
  key:
    access: ${JWT_ACCESS_KEY}
    refresh: ${JWT_REFRESH_KEY}
  max-age:
    access: 604800 #3시간 - 10800
    refresh: 604800 #일주일


jira:
  url: ${JIRA_URL} # Jira 인스턴스의 베이스 URL
  project:
    key: ${JIRA_PROJECT_KEY}
  user:
    email: ${JIRA_USER_EMAIL} # Jira API를 사용할 사용자의 이메일
  api:
    token: ${JIRA_API_TOKEN} # Jira API 토큰
