name: 테스트 요약본 생성

on: [push]

jobs:
  test_and_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Parse test results and generate markdown
      run: python .github/parse_tests.py > test_list.md

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add test_list.md
        git commit -m "Workflow : Test 결과 요약본 생성" -a || exit 0
        git push